-- =========================================================================================
-- CIRCUITO CREATIVO RUBÉN DARÍO - LEÓN, NICARAGUA
-- =========================================================================================

-- 1. Asegurar la existencia del Circuito Creativo de León
INSERT INTO public.creative_routes (
  id, municipality_id, name, slug, description, theme, difficulty,
  estimated_duration, points_award, badge_name, badge_icon, route_color, is_visible_in_map, status
)
SELECT 
  'route-dariana-leon',
  id,
  'Circuito Creativo Rubén Darío',
  'ruta-dariana-leon',
  'Circuito cultural por los hitos y espacios de memoria viva del Príncipe de las Letras Castellanas en León.',
  'Literatura & Patrimonio',
  'Fácil',
  120,
  200,
  'Caballero Dariano',
  'BookOpen',
  '#9333ea',
  true,
  'published'
FROM public.municipalities WHERE slug = 'leon'
ON CONFLICT (slug) DO NOTHING;

-- 2. Insertar los 10 sitios que conforman el circuito creativo (Si ya existen, no los duplica)
INSERT INTO public.route_places (
  municipality_id, route_id, name, slug, description, category, icon_name,
  address, walk_time, points_reward, lat, lng, order_num, is_primary_route_point, status, image_url
)
VALUES
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Casa Museo Archivo Rubén Darío',
    'casa-museo-archivo-ruben-dario',
    'Es la casa donde el «Príncipe de las Letras Castellanas» vivió durante su infancia y conserva manuscritos, primeras ediciones de sus libros y objetos personales.',
    'Museo Literario',
    'BookOpen',
    'De la Iglesia San Francisco 1c al oeste, León',
    '5 min a pie',
    80,
    12.4339000,
    -86.8798000,
    1,
    true,
    'active',
    'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Los Motivos del Lobo (Escultura)',
    'los-motivos-del-lobo-escultura',
    'Símbolo de la herencia literaria del poeta Rubén Darío, como un mensaje universal de convivencia y compasión, que invita a los visitantes a descubrir la riqueza cultural y espiritual que define la identidad nicaragüense.',
    'Escultura & Monumento',
    'Sparkles',
    'Costado norte del Parque Central, León',
    '2 min a pie',
    50,
    12.4368000,
    -86.8785000,
    2,
    true,
    'active',
    'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Centro Cultural Rubén Darío',
    'centro-cultural-ruben-dario-leon',
    'Espacio moderno inaugurado para la promoción del arte y la literatura, cuenta con biblioteca municipal, salón de robótica, áreas verdes, quiosco y aulas, ofreciendo un entorno ideal para la lectura y la tecnología.',
    'Centro Cultural',
    'Landmark',
    'Costado oeste de la Alcaldía de León',
    '4 min a pie',
    60,
    12.4358000,
    -86.8810000,
    3,
    true,
    'active',
    'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Teatro Municipal José de la Cruz Mena',
    'teatro-municipal-jose-de-la-cruz-mena',
    'Es el escenario principal para las artes escénicas, conciertos y eventos literarios que mantienen viva la rica herencia intelectual de la ciudad creativa de León, se realizan actividades mensuales, abierto al público en general.',
    'Artes Escénicas',
    'Sparkles',
    'Costado norte de la Catedral de León',
    '3 min a pie',
    70,
    12.4361000,
    -86.8795000,
    4,
    true,
    'active',
    'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Parque de los Poetas',
    'parque-de-los-poetas-leon',
    'Espacio histórico y cultural situado a dos cuadras de la Catedral, donde se rinde homenaje al «Príncipe de las Letras Castellanas» con una estatua central, rodeado por bustos de poetas leoneses, en un entorno de estilo colonial con jardines, que también ofrece gastronomía popular de la ciudad.',
    'Parque & Patrimonio',
    'Compass',
    'A dos cuadras al oeste de la Catedral de León',
    '3 min a pie',
    50,
    12.4342000,
    -86.8805000,
    5,
    true,
    'active',
    'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Vallas Informativas UNAN León',
    'vallas-informativas-unan-leon',
    'La exposición pictórica permanente de Rubén Darío en la UNAN-León consta de 14 vallas informativas, ubicadas en el jardín interior del edificio central, muestra la vida y obra del poeta, destacando su legado y su relación histórica con la institución. En este sitio se encuentran docentes a disposición de los visitantes para realizar un recorrido.',
    'Exposición & Academia',
    'BookOpen',
    'Edificio Central UNAN-León, jardín interior',
    '2 min a pie',
    50,
    12.4355000,
    -86.8778000,
    6,
    true,
    'active',
    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Basílica Catedral León, Tumba de Rubén Darío',
    'basilica-catedral-leon-tumba-dario',
    'Espacio de interés que recibe a visitantes por su estilo ecléctico, que mezcla barroco y neoclásico, donde se alberga la tumba del poeta Rubén Darío, situada al pie de la estatua de San Pablo, marcada por un león doliente esculpido por Jorge Navas Cordonero.',
    'Patrimonio de la Humanidad UNESCO',
    'Landmark',
    'Parque Central Juan José Quezada, León',
    'Punto de inicio',
    100,
    12.4350000,
    -86.8782000,
    7,
    true,
    'active',
    'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Escuela de Bellas Artes Mariana Sanson Arguello',
    'escuela-bellas-artes-mariana-sanson',
    'Destacado centro de formación artística, enfocado en el desarrollo técnico y creativo de niños, jóvenes y adultos. Ofrece clases en disciplinas como pintura, ballet, música (piano, violín, canto), teatro y percusión, con cafetería literaria.',
    'Centro de Formación Artística',
    'Sparkles',
    'Costado este del Parque San Francisco, León',
    '4 min a pie',
    60,
    12.4365000,
    -86.8765000,
    8,
    true,
    'active',
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Plazoleta Rubén Darío',
    'plazoleta-ruben-dario-leon',
    'Destaca por una escultura de 7 metros de altura del «Príncipe de las Letras Castellanas», creada por el escultor Sócrates Martínez, inspirada en su faceta diplomática. Escenario de actividades culturales los fines de semana.',
    'Plazoleta & Escultura',
    'Compass',
    'Avenida Rubén Darío, León',
    '6 min a pie',
    50,
    12.4330000,
    -86.8820000,
    9,
    true,
    'active',
    'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop'
  ),
  (
    (SELECT id FROM public.municipalities WHERE slug = 'leon'),
    (SELECT id FROM public.creative_routes WHERE slug = 'ruta-dariana-leon'),
    'Parque Centenario de la Dignidad Rubén Darío',
    'parque-centenario-dignidad-dario',
    'Espacio de referencia en la Ciudad Creativa de León, ubicado en la entrada sur (Carretera León-Managua), con imponente pórtico neoclásico, cuatro leones esculpidos, fuentes decorativas, jardines de buganvilias y placa-retrato del insigne poeta.',
    'Monumento & Espacio Público',
    'Landmark',
    'Entrada Sur de León (Carretera León-Managua)',
    '15 min en vehículo / transporte',
    70,
    12.4225000,
    -86.8700000,
    10,
    true,
    'active',
    'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800&auto=format&fit=crop'
  )
ON CONFLICT (slug) DO NOTHING;
